---
- name: Install Jenkins
  hosts: "jenkins_vm"
  become: yes 

  tasks:
    - name: Install java
      yum :
        name:  java-1.7.0-openjdk
        state: latest

    - name: Ensure Jenkins Repository is Installed
      yum_repository:
        name: jenkins
        state: present
        description: Official Jenkins Yum Repo
        baseurl: http://pkg.jenkins.io/redhat
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io-2023.key
        gpgcheck: yes
        enabled: yes
    - name: Ensure Jenkins is Installed
      yum :
        name: jenkins
        update_cache: yes
        state: present
#    - name: sleep for 30 seconds and continue with play
#      wait_for: timeout=30
#      delegate_to: localhost
    - name: Enable and Start the Jenkins Service
      service:
        name: jenkins
        enabled: yes
        state: start
#    - name: sleep for 30 seconds and continue with play
#      wait_for: timeout=30
#      delegate_to: localhost
    - name: Open Firewall Port
      firewalld:
        zone: public
        port: 8080/tcp
        permanent: true
        state: enabled
        immediate: true
    - name: init password jenkin
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result
    - name: print init password jenkins
      debug:
        var: result.stdout